

# This file was *autogenerated* from the file /Users/nathanielgreen/Desktop/Math/courses/galois_theory/programs/galois.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_16 = Integer(16)
var('X')

p = _sage_const_2 
Z_p = Integers(p)
Z_pX = PolynomialRing(Z_p, 'X')
f = Z_pX(X**_sage_const_4 +X+_sage_const_1 )

I = ideal(Z_pX, f)
Q = Z_pX.quotient(I)


alpha = Q(X)
for i in range(_sage_const_1 ,_sage_const_16 ):
    print(f"alpha^{i} = {alpha**i}")

